---
- name: Instalar servicios requeridos en el servidor víctima
  apt:
    name:
      - openssh-server
      - samba
      - apache2
      - xrdp
    state: present
    update_cache: yes

- name: Asegurar que los servicios estén iniciados y habilitados
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - ssh
    - smbd
    - apache2
    - xrdp

- name: Configurar Samba para compartir una carpeta pública (opcional)
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      [public]
      path = /srv/samba/public
      read only = no
      guest ok = yes
  notify: Restart smbd

- name: Crear carpeta pública para Samba (opcional)
  file:
    path: /srv/samba/public
    state: directory
    mode: '0777'
